server:
  port: 8080
spring:
  application:
    name: itlearn
  data:
    redis:
      host: localhost
      port: 6379
      password: yourpassword
      database: 0
  datasource:
    write:
      hikari:
        jbdc-url: jdbc:mysql://localhost:3306/itlearn?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: '!@#gmlfkr7236'
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 2
        maximum-pool-size: 10
        idle-timeout: 295000
        max-lifetime: 300000
        connection-timeout: 180000
        connection-test-query: select 1
    read:
      hikari:
        jbdc-url: jdbc:mysql://localhost:3306/itlearn?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
        username: root
        password: '!@#gmlfkr7236'
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 2
        maximum-pool-size: 10
        idle-timeout: 295000
        max-lifetime: 300000
        connection-timeout: 180000
        connection-test-query: select 1
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"

